### ISSUE TITLE
No implementation foud for method connect

### ISSUE THREAD

**Issue by mainstep** [Hiteshdon/mssql_connection#4]
Greetings,
in my web application written in Dart and Flutter, I am implementing the connection to a SQLServer server via mssql_connection.

When I use the "connect" method I get the following error:

"No implementation found for method connect on channel mssql_connection"

What can I do to solve the problem?
Thanks for your help

**Comment by Hiteshdon** [comment]
Hi there,

We understand you're encountering an issue with the mssql_connection plugin for web applications in your Flutter project. While we don't currently offer web platform support for this plugin due to security concerns raised by many experts, we'd be happy to suggest alternative solutions.  
For interacting with Microsoft SQL Server databases from your web application, a more secure approach is to use a Web API or RESTful API as an intermediary layer. This isolates your web application from the database and strengthens overall security. There are many resources available online to help you get started with building a Web API for SQL Server access.

**Comment by mainstep** [comment]
Good morning,
Thanks a lot for the answer.

I followed your advice and created a "bridge" between my application and the SQL server database.

Thank you very much for helping.
Good day
